### PR TITLE
Respect skipCertificateVerification

### LINKED ISSUE #16: Certificate verify issue on deskop
Example: https://annil_serverless.shuttleapp.rs

```
DioError [unknown]; null
Error: HandshakeException: Handshake error in client (OS Error:
CERTIFICATE_VERIFY_FAILED: Hostname mismatch(../../third_party/boringssl/src/ss|/handshake.cc:393))
```

When testing on ios, such issue does not occur.

### PR DESCRIPTION
**Pull request by snylonue**
fixes #16 

Only tested on windows, and I'm not sure why android build fails.

### CODE REVIEW

File: lib/services/annil/annil.dart [hunk 1]
```diff
@@ -16,15 +17,27 @@ import 'package:collection/collection.dart';
...
 
   List<LocalAnnilServer> servers = [];
   Map<int, String?> etags = {};
   List<String> albums = [];
 
   AnnilService(this.ref) {
-    _client.interceptors.add(RetryInterceptor(
-      dio: _client,
+    final config = ref.read(settingsProvider);
+    if (config.skipCertificateVerification.value) {
```
Comment (Yesterday17) [inline lib/services/annil/annil.dart]: `config.skipCertificateVerification.value` may change.

Comment (snylonue) [reply lib/services/annil/annil.dart]: I'm not familiar with flutter. Would `if (ref.read(settingsProvider).skipCertificateVerification.value) {}` work?

Comment (snylonue) [reply lib/services/annil/annil.dart]: Or pass `Ref` to `DownloadTask`?

Comment (Yesterday17) [reply lib/services/annil/annil.dart]: I think you should not use `config.skipCertificateVerification.value` with `if` statement here, but return an expression with `config.skipCertificateVerification.value` instead of `true`/`false`.

Comment (snylonue) [reply lib/services/annil/annil.dart]: updated

**Review by Yesterday17 — APPROVED** [review]
